nodeVersion: 24.16.0
engineStrict: true

packages:
  - packages/*
  - tests
  - bench
  - configs
  - docs
  - styled-system

allowBuilds:
  '@carbon/icon-helpers': true
  '@carbon/icons-react': true
  '@tsparticles/engine': true
  bun: true
  esbuild: true
  sharp: true
  unrs-resolver: true

overrides:
  # docs
  eslint>ajv: '^6.12.6'
  '@eslint/eslintrc>ajv': '^6.12.6'
