nodeVersion: 24.16.0
engineStrict: true

packages:
  - packages/*
  - tests
  - bench
  - configs
  - docs
  - styled-system

catalogs:
  oxc:
    oxfmt: ^0.56.0

allowBuilds:
  '@carbon/icon-helpers': true
  '@carbon/icons-react': true
  '@tsparticles/engine': true
  bun: true
  esbuild: true
  sharp: true
  unrs-resolver: true

auditConfig:
  # Only non-package related allowed here
  ignoreGhsas:
    - GHSA-h67p-54hq-rp68 # changeset
    - GHSA-qx2v-qp2m-jg93 # postcss (docs)

overrides:
  # pandacss
  brace-expansion: '>=5.0.6'
  # docs
  '@eslint/eslintrc>ajv': '^6.12.6'
  eslint>ajv: '^6.12.6'
