import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import type { PropsWithChildren, ReactNode } from 'react'
import './globals.css'

// TODO: Replace with Cerberus option
const poppins = Poppins({
  display: 'swap',
  subsets: ['latin'],
  weight: ['400', '600', '700', '800'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootProps {}

export default function RootLayout(props: PropsWithChildren<RootProps>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{props.children}</body>
    </html>
  )
}
