import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import type { PropsWithChildren } from 'react'
import { cerberusNextFontSettings } from '@cerberus-design/panda-preset'
import './globals.css'

const poppins = Poppins(cerberusNextFontSettings)

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootProps {}

export default function RootLayout(props: PropsWithChildren<RootProps>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{props.children}</body>
    </html>
  )
}
