export const components = [
  {
    id: '1.3',
    label: 'Components',
    href: '',
  },
  {
    id: '1.3.1',
    label: 'Accordion',
    slug: 'accordion',
    href: '/docs/components/accordion',
  },
  {
    id: '1.3.3',
    label: 'Admonition',
    slug: 'admonition',
    href: '/docs/components/admonition',
  },
  {
    id: '1.3.4',
    label: 'Avatar',
    slug: 'avatar',
    href: '/docs/components/avatar',
  },
  {
    id: '1.3.2',
    label: 'Button',
    slug: 'button',
    href: '/docs/components/button',
  },
  {
    id: '1.3.2a',
    label: 'Carousel',
    slug: 'carousel',
    href: '/docs/components/carousel',
  },
  {
    id: '1.3.5',
    label: 'Checkbox',
    slug: 'checkbox',
    href: '/docs/components/checkbox',
  },
  {
    id: '1.3.5b',
    label: 'Clipboard',
    slug: 'clipboard',
    href: '/docs/components/clipboard',
  },
  {
    id: '1.3.5a',
    label: 'Collapsible',
    slug: 'collapsible',
    href: '/docs/components/collapsible',
  },
  {
    id: '1.3.6',
    label: 'Combobox',
    slug: 'combobox',
    href: '/docs/components/combobox',
  },
  {
    id: '1.3.7',
    label: 'Confirm Modal',
    slug: 'confirm-modal',
    href: '/docs/components/confirm-modal',
  },
  {
    id: '1.3.8',
    label: 'CTAModal',
    slug: 'cta-modal',
    href: '/docs/components/cta-modal',
  },
  {
    id: '1.3.9',
    label: 'Date Picker',
    slug: 'date-picker',
  },
  {
    id: '1.3.10',
    label: 'Dialog',
    slug: 'dialog',
    href: '/docs/components/dialog',
  },
  {
    id: '1.3.11',
    label: 'Field',
    slug: 'field',
    href: '/docs/components/field',
  },
  {
    id: '1.3.12',
    label: 'Fieldset',
    slug: 'fieldset',
    href: '/docs/components/fieldset',
  },
  {
    id: '1.3.13',
    label: 'File Uploader',
    slug: 'file-uploader',
    href: '/docs/components/file-uploader',
  },
  {
    id: '1.3.14',
    label: 'Icon Button',
    slug: 'icon-button',
    href: '/docs/components/icon-button',
  },
  {
    id: '1.3.15',
    label: 'Input',
    slug: 'input',
    href: '/docs/components/input',
  },
  {
    id: '1.3.31',
    label: 'Loading States',
    slug: 'loading-states',
    href: '/docs/components/loading-states',
  },
  {
    id: '1.3.16',
    label: 'Menu',
    slug: 'menu',
    href: '/docs/components/menu',
  },
  {
    id: '1.3.17',
    label: 'Notifications',
    slug: 'notifications',
    href: '/docs/components/notifications',
  },
  {
    id: '1.3.17a',
    label: 'Number Input',
    slug: 'number-input',
    href: '/docs/components/number-input',
  },
  {
    id: '1.3.17c',
    label: 'Pagination',
    slug: 'pagination',
    href: '/docs/components/pagination',

    tag: 'new',
  },
  {
    id: '1.3.17b',
    label: 'Pin Input',
    slug: 'pin-input',
    href: '/docs/components/pin-input',
  },
  {
    id: '1.3.18',
    label: 'Progress',
    slug: 'progress',
    href: '/docs/components/progress',
  },
  {
    id: '1.3.19',
    label: 'Prompt Modal',
    slug: 'prompt-modal',
    href: '/docs/components/prompt-modal',
  },
  {
    id: '1.3.20',
    label: 'Radio',
    slug: 'radio',
    href: '/docs/components/radio',
  },
  {
    id: '1.3.21',
    label: 'Rating',
    slug: 'rating',
    href: '/docs/components/rating',
  },
  {
    id: '1.3.22',
    label: 'Select',
    slug: 'select',
    href: '/docs/components/select',
  },
  {
    id: '1.3.22a',
    label: 'Split Button',
    slug: 'split-button',
    href: '/docs/components/split-button',
  },
  {
    id: '1.3.23',
    label: 'Switch',
    slug: 'switch',
    href: '/docs/components/switch',
  },
  {
    id: '1.3.24',
    label: 'Table',
    slug: 'table',
    href: '/docs/components/table',
  },
  {
    id: '1.3.25',
    label: 'Tabs',
    slug: 'tabs',
    href: '/docs/components/tabs',
  },
  {
    id: '1.3.26',
    label: 'Tag',
    slug: 'tag',
    href: '/docs/components/tag',
  },
  {
    id: '1.3.27',
    label: 'Text',
    slug: 'text',
    href: '/docs/components/text',
  },
  {
    id: '1.3.28',
    label: 'Textarea',
    slug: 'textarea',
    href: '/docs/components/textarea',
  },
  {
    id: '1.3.29',
    label: 'Toggle',
    slug: 'toggle',
    href: '/docs/components/toggle',
  },
  {
    id: '1.3.30',
    label: 'Tooltip',
    slug: 'tooltip',
    href: '/docs/components/tooltip',
  },
]
