export const utilities = [
  {
    id: '1.4',
    label: 'Utilities',
    href: '',
  },
  {
    id: '1.4.1a',
    label: 'Client Only',
    slug: 'client-only',
    href: '/docs/components/client-only',
  },
  {
    id: '1.4.1b',
    label: 'Download Trigger',
    slug: 'download-trigger',
    href: '/docs/components/download-trigger',
  },
  {
    id: '1.4.1c',
    label: 'Environment',
    slug: 'environment',
    href: '/docs/components/environment',
  },
  {
    id: '1.4.1',
    label: 'Feature Flags',
    slug: 'feature-flags',
    href: '/docs/components/feature-flags',
  },
  {
    id: '1.4.1d',
    label: 'Focus Trap',
    slug: 'focus-trap',
    href: '/docs/components/focus-trap',
  },
  {
    id: '1.4.2',
    label: 'For',
    slug: 'for',
    href: '/docs/components/for',
  },
  {
    id: '1.4.3e',
    label: 'Format Byte',
    slug: 'format-byte',
    href: '/docs/components/format-byte',
  },
  {
    id: '1.4.4f',
    label: 'Format Number',
    slug: 'format-number',
    href: '/docs/components/format-number',
  },
  {
    id: '1.4.5g',
    label: 'Format Relative Time',
    slug: 'format-relative-time',
    href: '/docs/components/format-relative-time',
  },
  {
    id: '1.4.5h',
    label: 'Frame',
    slug: 'frame',
    href: '/docs/components/frame',
  },
  {
    id: '1.4.5i',
    label: 'Highlight',
    slug: 'highlight',
    href: '/docs/components/highlight',
  },
  {
    id: '1.4.5j',
    label: 'JSON Tree View',
    slug: 'json-tree-view',
    href: '/docs/components/json-tree-view',
  },
  {
    id: '1.4.5k',
    label: 'Locale',
    slug: 'locale',
    href: '/docs/components/locale',
  },
  {
    id: '1.4.3',
    label: 'Local Storage',
    slug: 'local-storage',
    href: '/docs/components/local-storage',
  },
  {
    id: '1.4.4',
    label: 'Portal',
    slug: 'portal',
    href: '/docs/components/portal',
  },
  {
    id: '1.4.5l',
    label: 'Presence',
    slug: 'presence',
    href: '/docs/components/presence',
  },
  {
    id: '1.4.6',
    label: 'Show',
    slug: 'show',
    href: '/docs/components/show',
  },
  {
    id: '1.4.6',
    label: 'splitProps',
    slug: 'split-props',
    href: '/docs/components/split-props',
  },
  {
    id: '1.4.7',
    label: 'Theme',
    slug: 'theme',
    href: '/docs/components/theme',
  },
]
