export function JsrLogo() {
  return (
    <svg viewBox="-2 -2 17 11" aria-hidden="true">
      <rect
        x="4"
        y="0"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="5"
        y="0"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="6"
        y="0"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="7"
        y="0"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="8"
        y="0"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="2"
        y="1"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect x="3" y="1" width="1" height="1" fill="transparent"></rect>
      <rect
        x="4"
        y="1"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect x="5" y="1" width="1" height="1" fill="transparent"></rect>
      <rect x="6" y="1" width="1" height="1" fill="transparent"></rect>
      <rect x="7" y="1" width="1" height="1" fill="transparent"></rect>
      <rect
        x="8"
        y="1"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="9"
        y="1"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="10"
        y="1"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="11"
        y="1"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="12"
        y="1"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="0"
        y="2"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="1"
        y="2"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="2"
        y="2"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect x="3" y="2" width="1" height="1" fill="transparent"></rect>
      <rect
        x="4"
        y="2"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect x="5" y="2" width="1" height="1" fill="transparent"></rect>
      <rect
        x="6"
        y="2"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="7"
        y="2"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="8"
        y="2"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect x="9" y="2" width="1" height="1" fill="transparent"></rect>
      <rect x="10" y="2" width="1" height="1" fill="transparent"></rect>
      <rect x="11" y="2" width="1" height="1" fill="transparent"></rect>
      <rect
        x="12"
        y="2"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="0"
        y="3"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect x="1" y="3" width="1" height="1" fill="transparent"></rect>
      <rect
        x="2"
        y="3"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect x="3" y="3" width="1" height="1" fill="transparent"></rect>
      <rect
        x="4"
        y="3"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect x="5" y="3" width="1" height="1" fill="transparent"></rect>
      <rect x="6" y="3" width="1" height="1" fill="transparent"></rect>
      <rect x="7" y="3" width="1" height="1" fill="transparent"></rect>
      <rect
        x="8"
        y="3"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect x="9" y="3" width="1" height="1" fill="transparent"></rect>
      <rect
        x="10"
        y="3"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect x="11" y="3" width="1" height="1" fill="transparent"></rect>
      <rect
        x="12"
        y="3"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="0"
        y="4"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect x="1" y="4" width="1" height="1" fill="transparent"></rect>
      <rect x="2" y="4" width="1" height="1" fill="transparent"></rect>
      <rect x="3" y="4" width="1" height="1" fill="transparent"></rect>
      <rect
        x="4"
        y="4"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="5"
        y="4"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="6"
        y="4"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect x="7" y="4" width="1" height="1" fill="transparent"></rect>
      <rect
        x="8"
        y="4"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect x="9" y="4" width="1" height="1" fill="transparent"></rect>
      <rect
        x="10"
        y="4"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="11"
        y="4"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="12"
        y="4"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="0"
        y="5"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="1"
        y="5"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="2"
        y="5"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="3"
        y="5"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="4"
        y="5"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect x="5" y="5" width="1" height="1" fill="transparent"></rect>
      <rect x="6" y="5" width="1" height="1" fill="transparent"></rect>
      <rect x="7" y="5" width="1" height="1" fill="transparent"></rect>
      <rect
        x="8"
        y="5"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect x="9" y="5" width="1" height="1" fill="transparent"></rect>
      <rect
        x="10"
        y="5"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="4"
        y="6"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="5"
        y="6"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="6"
        y="6"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="7"
        y="6"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="8"
        y="6"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="9"
        y="6"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
      <rect
        x="10"
        y="6"
        width="1"
        height="1"
        fill="var(--cerberus-colors-page-text-100)"
      ></rect>
    </svg>
  )
}
