/*
 * --------------------------------------------------------
 * WARNING: This file is generated by the Figma plugin.
 * Do not edit this file manually - it will be overwritten.
 * --------------------------------------------------------
 */

export const collection = {
  baseCollectionId: 'VariableCollectionId:24332:15023',
  defaultModeId: 'VariableCollectionId:24332:15032/24332:8',
  hiddenFromPublishing: false,
  id: 'VariableCollectionId:24332:15032',
  isExtension: true,
  key: '97fa122cf0036922455f762527c7c11668b7ceb7',
  modes: [
    {
      modeId: 'VariableCollectionId:24332:15032/24332:8',
      name: 'compact',
      parentModeId: '24332:5',
    },
    {
      modeId: 'VariableCollectionId:24332:15032/24332:9',
      name: 'default',
      parentModeId: '24332:6',
    },
  ],
  name: 'body-md',
  parentVariableCollectionId: 'VariableCollectionId:24332:15023',
  relatedVariableIds: {
    'VariableID:24332:15028': 'VariableOverrideId:24332:15033',
    'VariableID:24332:15029': 'VariableOverrideId:24332:15034',
    'VariableID:24332:15030': 'VariableOverrideId:24332:15035',
    'VariableID:24332:15031': 'VariableOverrideId:24332:15036',
  },
  remote: false,
  rootVariableCollectionId: 'VariableCollectionId:24332:15023',
  variableIds: [
    'VariableID:24332:15027',
    'VariableID:24332:15028',
    'VariableID:24332:15029',
    'VariableID:24332:15030',
    'VariableID:24332:15031',
  ],
  variableOverrides: {
    'VariableID:24332:15028': {
      'VariableCollectionId:24332:15032/24332:8': {
        id: 'VariableID:22530:11733',
        type: 'VARIABLE_ALIAS',
      },
      'VariableCollectionId:24332:15032/24332:9': {
        id: 'VariableID:6959:25445',
        type: 'VARIABLE_ALIAS',
      },
    },
    'VariableID:24332:15029': {
      'VariableCollectionId:24332:15032/24332:8': {
        id: 'VariableID:22530:11728',
        type: 'VARIABLE_ALIAS',
      },
      'VariableCollectionId:24332:15032/24332:9': {
        id: 'VariableID:22530:11742',
        type: 'VARIABLE_ALIAS',
      },
    },
    'VariableID:24332:15030': {
      'VariableCollectionId:24332:15032/24332:8': 3.1103997230529785,
      'VariableCollectionId:24332:15032/24332:9': 1.2000000476837158,
    },
    'VariableID:24332:15031': {
      'VariableCollectionId:24332:15032/24332:8': 1,
      'VariableCollectionId:24332:15032/24332:9': -1,
    },
  },
} as const

export const modes = {
  'VariableCollectionId:24332:15032/24332:8': {
    modeId: 'VariableCollectionId:24332:15032/24332:8',
    name: 'compact',
    parentModeId: '24332:5',
  },
  'VariableCollectionId:24332:15032/24332:9': {
    modeId: 'VariableCollectionId:24332:15032/24332:9',
    name: 'default',
    parentModeId: '24332:6',
  },
  compact: 'VariableCollectionId:24332:15032/24332:8',
  default: 'VariableCollectionId:24332:15032/24332:9',
} as const

export const tokens = {
  font: {
    codeSyntax: {},
    description: '',
    hiddenFromPublishing: true,
    id: 'VariableID:24332:15027',
    key: 'f9b0263aa73330137d55e223a14cbee81b339f16',
    name: 'font',
    remote: false,
    resolvedType: 'STRING',
    scopes: [],
    valuesByMode: {
      'VariableCollectionId:24332:15032/24332:8': 'brand-font',
      'VariableCollectionId:24332:15032/24332:9': 'monospace',
    },
    variableCollectionId: 'VariableCollectionId:24332:15023',
  },
  'font-size': {
    codeSyntax: {},
    description: '',
    hiddenFromPublishing: true,
    id: 'VariableID:24332:15028',
    key: '5bff48788a4cdf5b7b12850778c1ce1490d4ea57',
    name: 'font-size',
    remote: false,
    resolvedType: 'FLOAT',
    scopes: [],
    valuesByMode: {
      'VariableCollectionId:24332:15032/24332:8': '10',
      'VariableCollectionId:24332:15032/24332:9': '20',
    },
    variableCollectionId: 'VariableCollectionId:24332:15023',
  },
  'font-weight': {
    codeSyntax: {},
    description: '',
    hiddenFromPublishing: true,
    id: 'VariableID:24332:15029',
    key: '38ec5369d1e08129e23e56b5bca0179cae78a378',
    name: 'font-weight',
    remote: false,
    resolvedType: 'FLOAT',
    scopes: [],
    valuesByMode: {
      'VariableCollectionId:24332:15032/24332:8': '600',
      'VariableCollectionId:24332:15032/24332:9': '1000',
    },
    variableCollectionId: 'VariableCollectionId:24332:15023',
  },
  'letter-spacing': {
    codeSyntax: {},
    description: '',
    hiddenFromPublishing: true,
    id: 'VariableID:24332:15031',
    key: '54a814e03eee41939d9f33c4f2177c3a668f01a7',
    name: 'letter-spacing',
    remote: false,
    resolvedType: 'FLOAT',
    scopes: [],
    valuesByMode: {
      'VariableCollectionId:24332:15032/24332:8': 1,
      'VariableCollectionId:24332:15032/24332:9': -1,
    },
    variableCollectionId: 'VariableCollectionId:24332:15023',
  },
  'line-height': {
    codeSyntax: {},
    description: '',
    hiddenFromPublishing: true,
    id: 'VariableID:24332:15030',
    key: 'c6a9672a008c7f5d2e8aea934bc119de6a9f3eba',
    name: 'line-height',
    remote: false,
    resolvedType: 'FLOAT',
    scopes: [],
    valuesByMode: {
      'VariableCollectionId:24332:15032/24332:8': 3.1103997230529785,
      'VariableCollectionId:24332:15032/24332:9': 1.2000000476837158,
    },
    variableCollectionId: 'VariableCollectionId:24332:15023',
  },
} as const
