/*
 * --------------------------------------------------------
 * WARNING: This file is generated by the Figma plugin.
 * Do not edit this file manually - it will be overwritten.
 * --------------------------------------------------------
 */

export const collection = {
  defaultModeId: '22126:1',
  hiddenFromPublishing: false,
  id: 'VariableCollectionId:22126:15112',
  isExtension: false,
  key: '1295c266827fc09a402683311a612201185ef814',
  modes: [
    { modeId: '22126:3', name: 'general-sans' },
    { modeId: '24103:0', name: 'montserrat' },
    { modeId: '22141:2', name: 'nunito' },
    { modeId: '22126:1', name: 'poppins' },
  ],
  name: 'font-family',
  remote: false,
  variableIds: ['VariableID:22126:15113', 'VariableID:22126:15114'],
} as const

export const modes = {
  '22126:1': { modeId: '22126:1', name: 'poppins' },
  '22126:3': { modeId: '22126:3', name: 'general-sans' },
  '22141:2': { modeId: '22141:2', name: 'nunito' },
  '24103:0': { modeId: '24103:0', name: 'montserrat' },
  'general-sans': '22126:3',
  montserrat: '24103:0',
  nunito: '22141:2',
  poppins: '22126:1',
} as const

export const tokens = {
  'brand-font': {
    codeSyntax: {},
    description: '',
    hiddenFromPublishing: false,
    id: 'VariableID:22126:15113',
    key: '7eb689919bb93998de7c4641a6b12b9860230fb9',
    name: 'brand-font',
    remote: false,
    resolvedType: 'STRING',
    scopes: ['FONT_FAMILY'],
    valuesByMode: {
      '22126:1': 'Poppins',
      '22126:3': 'General Sans Variable',
      '22141:2': 'Nunito Sans',
      '24103:0': 'montserrat',
    },
    variableCollectionId: 'VariableCollectionId:22126:15112',
  },
  monospace: {
    codeSyntax: {},
    description: '',
    hiddenFromPublishing: false,
    id: 'VariableID:22126:15114',
    key: '95e80ef4a103adf20e332612bce4944f46cb68cb',
    name: 'monospace',
    remote: false,
    resolvedType: 'STRING',
    scopes: ['FONT_FAMILY'],
    valuesByMode: {
      '22126:1': 'Recursive',
      '22126:3': 'Recursive',
      '22141:2': 'Recursive',
      '24103:0': 'Recursive',
    },
    variableCollectionId: 'VariableCollectionId:22126:15112',
  },
} as const
