/*
 * --------------------------------------------------------
 * WARNING: This file is generated by the Figma plugin.
 * Do not edit this file manually - it will be overwritten.
 * --------------------------------------------------------
 */

export const collection = {
  defaultModeId: '24332:5',
  hiddenFromPublishing: false,
  id: 'VariableCollectionId:24332:15023',
  isExtension: false,
  key: '79b9f1f9384c5326e4747fa00be8010c2b13db2f',
  modes: [
    { modeId: '24332:5', name: 'compact' },
    { modeId: '24332:6', name: 'default' },
  ],
  name: 'wip-text-styles',
  remote: false,
  variableIds: [
    'VariableID:24332:15027',
    'VariableID:24332:15028',
    'VariableID:24332:15029',
    'VariableID:24332:15030',
    'VariableID:24332:15031',
  ],
} as const

export const modes = {
  '24332:5': { modeId: '24332:5', name: 'compact' },
  '24332:6': { modeId: '24332:6', name: 'default' },
  compact: '24332:5',
  default: '24332:6',
} as const

export const tokens = {
  font: {
    codeSyntax: {},
    description: '',
    hiddenFromPublishing: true,
    id: 'VariableID:24332:15027',
    key: 'f9b0263aa73330137d55e223a14cbee81b339f16',
    name: 'font',
    remote: false,
    resolvedType: 'STRING',
    scopes: [],
    valuesByMode: { '24332:5': 'brand-font', '24332:6': 'monospace' },
    variableCollectionId: 'VariableCollectionId:24332:15023',
  },
  'font-size': {
    codeSyntax: {},
    description: '',
    hiddenFromPublishing: true,
    id: 'VariableID:24332:15028',
    key: '5bff48788a4cdf5b7b12850778c1ce1490d4ea57',
    name: 'font-size',
    remote: false,
    resolvedType: 'FLOAT',
    scopes: [],
    valuesByMode: { '24332:5': '16', '24332:6': '56' },
    variableCollectionId: 'VariableCollectionId:24332:15023',
  },
  'font-weight': {
    codeSyntax: {},
    description: '',
    hiddenFromPublishing: true,
    id: 'VariableID:24332:15029',
    key: '38ec5369d1e08129e23e56b5bca0179cae78a378',
    name: 'font-weight',
    remote: false,
    resolvedType: 'FLOAT',
    scopes: [],
    valuesByMode: { '24332:5': '1000', '24332:6': '300' },
    variableCollectionId: 'VariableCollectionId:24332:15023',
  },
  'letter-spacing': {
    codeSyntax: {},
    description: '',
    hiddenFromPublishing: true,
    id: 'VariableID:24332:15031',
    key: '54a814e03eee41939d9f33c4f2177c3a668f01a7',
    name: 'letter-spacing',
    remote: false,
    resolvedType: 'FLOAT',
    scopes: [],
    valuesByMode: { '24332:5': 2, '24332:6': 4 },
    variableCollectionId: 'VariableCollectionId:24332:15023',
  },
  'line-height': {
    codeSyntax: {},
    description: '',
    hiddenFromPublishing: true,
    id: 'VariableID:24332:15030',
    key: 'c6a9672a008c7f5d2e8aea934bc119de6a9f3eba',
    name: 'line-height',
    remote: false,
    resolvedType: 'FLOAT',
    scopes: [],
    valuesByMode: { '24332:5': 18, '24332:6': 1.7999999523162842 },
    variableCollectionId: 'VariableCollectionId:24332:15023',
  },
} as const
