export const items = [
  {
    id: '0.0',
    label: 'Get Started',
    href: '',
  },
  {
    id: '0.1',
    href: '/docs/signals/overview',
    label: 'Overview',
    slug: 'overview',
  },
  {
    id: '0.2',
    href: '/docs/signals/reactivity',
    label: 'Reactivity',
    slug: 'reactivity',
  },
  {
    id: '0.3',
    href: '/docs/signals/data-fetching',
    label: 'Data Fetching',
    slug: 'data-fetching',
  },
  {
    id: '0.4',
    href: '/docs/signals/stores',
    label: 'Stores',
    slug: 'stores',
  },
  {
    id: '1.0',
    label: 'Primitives',
    href: '',
  },
  {
    id: '1.1',
    href: '/docs/signals/create-signal',
    label: 'createSignal',
    slug: 'create-signal',
  },
  {
    id: '1.2',
    href: '/docs/signals/create-query',
    label: 'createQuery',
    slug: 'create-query',
  },
  {
    id: '1.3',
    href: '/docs/signals/create-mutation',
    label: 'createMutation',
    slug: 'create-mutation',
  },
  {
    id: '1.4',
    href: '/docs/signals/create-computed',
    label: 'createComputed',
    slug: 'create-computed',
  },
  {
    id: '1.5',
    href: '/docs/signals/create-effect',
    label: 'createEffect',
    slug: 'create-effect',
  },
  {
    id: '1.6',
    href: '/docs/signals/create-store-context',
    label: 'createStoreContext',
    slug: 'create-store-context',
  },
  {
    id: '1.7',
    href: '/docs/signals/batch',
    label: 'batch',
    slug: 'batch',
  },
  {
    id: '1.8',
    href: '/docs/signals/on-cleanup',
    label: 'onCleanup',
    slug: 'on-cleanup',
  },
  {
    id: '1.9',
    href: '/docs/signals/untrack',
    label: 'untrack',
    slug: 'untrack',
  },
  {
    id: '2.0',
    label: 'Hooks',
    href: '',
  },
  {
    id: '2.1',
    href: '/docs/signals/use-query',
    label: 'useQuery',
    slug: 'use-query',
  },
  {
    id: '2.2',
    href: '/docs/signals/use-mutation',
    label: 'useMutation',
    slug: 'use-mutation',
  },
  {
    id: '2.3',
    href: '/docs/signals/use-read',
    label: 'useRead',
    slug: 'use-read',
  },
  {
    id: '2.4',
    href: '/docs/signals/use-signal',
    label: 'useSignal',
    slug: 'use-signal',
  },
  {
    id: '2.5',
    href: '/docs/signals/use-store',
    label: 'useStore',
    slug: 'use-store',
  },
  {
    id: '3.0',
    label: 'Components',
    href: '',
  },
  {
    id: '3.1',
    href: '/docs/signals/reactive-text',
    label: 'ReactiveText',
    slug: 'reactive-text',
  },
]
