import {
  ArrowRight,
  Calendar,
  CaretDown,
  Checkmark,
  CheckmarkFilled,
  CheckmarkOutline,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Close,
  CloudUpload,
  Column,
  ErrorFilled,
  Filter,
  FilterEdit,
  FilterRemove,
  Information,
  InformationFilled,
  OverflowMenuVertical,
  Restart,
  Search,
  TableSplit,
  TrashCan,
  UserFilled,
  ViewOff,
  Warning,
  WarningAlt,
  WarningFilled,
} from '@carbon/icons-react'
import { AnimatingUploadIcon } from '../../components/AnimatingUploadIcon'
import { DefinedIcons } from '../types'
import { CheckmarkIcon, IndeterminateIcon } from './checkbox.icons'
import {
  PinLeftFilledIcon,
  PinLeftIcon,
  PinRightFilledIcon,
  PinRightIcon,
} from './pinned.icons'
import { SortAscIcon, SortDescIcon } from './sort.icons'

/**
 * Fallback icons when there is no custom set provided by the user.
 */
export const defaultIcons: Required<DefinedIcons> = {
  accordionIndicator: ChevronDown,
  arrowRight: ArrowRight,
  avatar: UserFilled,
  calendar: Calendar,
  calendarPrev: ChevronLeft,
  calendarNext: ChevronRight,
  caretDown: CaretDown,
  checkbox: CheckmarkIcon,
  close: Close,
  column: Column,
  confirmModal: Information,
  dangerNotification: WarningFilled,
  decrement: ChevronDown,
  delete: TrashCan,
  error: ErrorFilled,
  fileUploader: AnimatingUploadIcon,
  filter: Filter,
  filterEdit: FilterEdit,
  filterClear: FilterRemove,
  increment: ChevronUp,
  indeterminate: IndeterminateIcon,
  info: InformationFilled,
  infoNotification: Information,
  invalid: WarningFilled,
  invalidAlt: Warning,
  moreVertical: OverflowMenuVertical,
  pinLeft: PinLeftIcon,
  pinLeftFilled: PinLeftFilledIcon,
  pinRight: PinRightIcon,
  pinRightFilled: PinRightFilledIcon,
  promptModal: Information,
  redo: Restart,
  search: Search,
  selectArrow: ChevronDown,
  selectChecked: Checkmark,
  sortAsc: SortAscIcon,
  sortDesc: SortDescIcon,
  success: CheckmarkFilled,
  successNotification: CheckmarkOutline,
  table: TableSplit,
  toggleChecked: Checkmark,
  viewOff: ViewOff,
  waitingFileUploader: CloudUpload,
  warningNotification: WarningAlt,
  warning: WarningFilled,
}
