name: 🧪 Publish Pre-Release

on:
  push:
    branches:
      - main
    # Ignore the bot PR commits to prevent infinite loops
    paths-ignore:
      - '.changeset/**'
      - '**/package.json'
      - '**/deno.json'
      - 'CHANGELOG.md'

env:
  CI: true
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  snapshot:
    name: Build & Publish Canary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          node-version: 26
      - uses: denoland/setup-deno@v2
        with:
          cache: true
      - uses: oven-sh/setup-bun@v2

      - run: pnpm install && deno install

      # Generates 0.0.0-next-TIMESTAMP
      - name: Generate Canary Versions
        run: pnpm changeset version --snapshot next

      - name: Sync Deno Versions
        run: pnpm run ci:version

      - name: Publish Canary Packages
        run: |
          # NPM Releases (using the 'next' tag)
          # ORDER MATTERS
          cd packages/react && pnpm build && pnpm publish --tag next --no-git-checks
          cd ../signals && pnpm build && pnpm publish --tag next --no-git-checks
          cd ../data-grid && pnpm build && pnpm publish --tag next --no-git-checks

          # JSR Releases (Deno naturally picks up the canary version string)
          # ORDER MATTERS
          cd ../figma && deno publish --allow-dirty
          cd ../tokens && deno publish --allow-dirty
          cd ../preset-acheron-theme && deno publish --allow-dirty
          cd ../preset-cerberus-theme && deno publish --allow-dirty
          cd ../preset-elysium-theme && deno publish --allow-dirty
          cd ../panda-preset && deno publish --allow-dirty
