name: Sync Figma variables to tokens

on:
  push:
    branches:
      - main

env:
  CI: true
  FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
  HUSKY: 0 # Instructs Husky to skip hooks in this environment

jobs:
  sync-figma-to-tokens:
    runs-on: ubuntu-latest
    # CIRCUIT BREAKER: Do not run if the commit came from our bot's PR
    if: "!contains(github.event.head_commit.message, 'update tokens from Figma')"
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          cache: 'pnpm'
          node-version: '22'

      - name: Install dependencies
        run: pnpm install

      - name: Sync variables in Figma file to tokens
        run: pnpm run figma:sync
        working-directory: ./packages/figma

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: 'chore: update tokens from Figma'
          title: '[chore]: update tokens from Figma'
          body: 'This PR updates the latest tokens from Figma.'
          branch: chore/update-tokens
